language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab1-set
  - make -j
  - cd ../mp2-lab1-set/test_set
notifications:
  email: false
